spring.datasource.url=jdbc:postgresql://dpg-d88rfrnavr4c73934ho0-a.singapore-postgres.render.com:5432/hospital_db_jc6t

spring.datasource.username=hospital_db_jc6t_user

spring.datasource.password=tntxIPRF0PC80KghcZ5n9NenI4jpFtk7

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080